name: Deploy to Hostinger

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Files
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout Code
        uses: actions/checkout@v4

      - name: 📂 Sync files to Hostinger
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: domains/ralaikoa.com/public_html/muzik/
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            **/.env
